---
title: "ECON 626: Problem Set 2"
#author: "Paul Schrimpf"
date: 2025-09-23
bibliography: ../../626.bib
---

$$
\def\R{{\mathbb{R}}}
\def\Er{{\mathrm{E}}}
$$

# Problem 1

Let $X_{1},...,X_{n}$ be independent and identically distribution and $P(X_{1}\leq t)=F(t)$ for some function $F$. Then, write the probability
$P(\max_{1\leq i\leq n}X_{i}\leq t)$ in terms of $F$.

# Problem 2

1. Show that if $E[Y |X] = 0$, then $Y$ and $g(X)$ are uncorrelated for any (Borel) measurable
function $g$. Do you have the same conclusion if we weaken the condition $E[Y |X] = 0$ to
$E[Y |X] = a$ for some fixed constant $a \in \R$?

2. Suppose that $E[Y^2 |X] < a^2$ for some constant $a > 0$. Then, show that for any $b > 0$,
$$
P\left(|Y − EY | > b\right) \leq \frac{a^2}{b^2}.
$$

3. Show that if $E[Y | \exp(X)] = E[Y]$, then the correlation between
$E[Y | cos(X)]$ and $cos(X)$ is zero.

# Problem 3

Let $X: \Omega \to \R$, $W:  \Omega \to \R$, $Z: \Omega \to \R$, and $D: \Omega \to \{0, 1\}$ be random variables.
Let $Y = D X + (1-D) W$.  Suppose that $Y$, $D$, and $Z$ are observed, but $X$ and $W$ are not.

1. Suppose $D$ is independent of $X$, $W$.  Then show that $\Er[X - W]$ is identified.

2. Suppose $Z$ is independent of $X$ and $W$, and
$\exists E_1, E_0 \in \sigma(Z)$ such that $P(D=1 | E_1) = 1$ and  $P(D=0|E_0) = 1$.
Then show that $\Er[X-W]$ is identified.
