---
title: "Probability"
author: "Paul Schrimpf"
date: last-modified
format:
  revealjs:
    theme: moon
    width: 1820
    height: 1000
    min-scale: 0.1
bibliography: ../626.bib

jupyter: julia-1.8
execute:
  cache: false
---

## Reading

- **@song2021 chapter 2** (which is the basis for these slides)
- @pollard2002

# Probability

## Probability Space

::: {.callout-tip icon=false}

### Definitions

- Given a measure space $(\Omega ,\mathscr{F})$, a **probability** (or **probability measure**)$\ P$ is a
measure s.t. $P(\Omega )=1$
-  $(\Omega ,\mathscr{F}, P)$ is a **probability space**
- $\Omega$ is a **sample space**
- $\omega \in \Omega$ is an **outcome**
- $A \in \mathscr{F}$ is an **event**

:::

---

::: {.callout-note icon=false}

### Exercise

Show $\forall A, B \in \mathscr{F}$
1. $P(\varnothing )=0$
2. $P(A)\leq 1.$
3. $P(A^{c})=1-P(A)$
4. $P(A\cup B)=P(A)+P(B)-P(A\cap B)$
5. If $A\subset B$, then $P(A)\leq P(B)$
6. $P(B\cap A^{c})=P(B)-P(A\cap B)$

:::

# Random Variables

## Random Variable

::: {.callout-tip icon=false}

### Definition

A **random variable** $X$ is a measurable function from $\Omega$ to $\mathbf{R}$

:::

## Distribution

::: {.callout-tip icon=false}

### Definition

Let $(\Omega ,\mathscr{F},P)$ be a probability space, $X$ a random variable on $(\Omega ,\mathscr{F})$.
A **distribution** $P_{X}$ induced by $X$ is a probability measure on $(\mathbf{R},\mathscr{B}(\mathbf{R}))$ such
that : $\forall B\in \mathscr{B}(\mathbf{R})$,
$$
P_{X}(B)\equiv P\left\{ \omega \in \Omega :X(\omega )\in B\right\}
$$

:::

## Distribution Function

::: {.callout-tip icon=false}

### Definition

The CDF of a random variable $X$ with
distribution $P_{X}$ is defined to be a function
$F:\mathbf{R}\rightarrow [0,1]$ such that
$$
F(t)=P_{X}\left( (-\infty ,t]\right) .
$$

:::

## Stochastic Dominance

::: {.callout-tip icon=false}

### Definition

Suppose that two random variables $X_1$ and $X_2$ have CDFs $F_1$ and $F_2$.

1. Suppose that $F_1(x) \le F_2(x)$ for all $x \in \mathbf{R}$. Then $X_1$ **first order stochastically dominates (FOSD)** $X_2$.

2. Suppose that for all $y \in \mathbf{R}$,
$$
		\int_{-\infty}^y F_1(x) dx \le \int_{-\infty}^y F_2(x) dx.
$$
    Then $X_1$ **second order stochastically dominates (SOSD)** $X_2$
:::

## Density

::: {.callout-tip icon=false}

### Definition

(i) Let $X$ be a random variable with
distribution $P_{X}$. When $P_{X}\ll \lambda$, we call $X$ a
**continuous random variable**, and call the Radon-Nikodym derivative
$f\equiv dP_{X}/d\lambda$ the (probability) **density function** of $P_{X}$.

(ii) We say that $X$ is a **discrete random variable**, if
there exists a countable set $A\subset \mathbf{R}$ and such that
$P_{X}A^{c}=0$

:::

::: {.notes}

Density wrt to other measures? e.g. dirac?

:::

---

::: {.callout-note icon=false}

### Exercise

Show that when $X$ is continuous, its CDF is a continuous function

:::

<!--- TODO: add examples or uses to go with these definitions --->

# Expectation

# Inequalities



# References
