---
title: "ECON 626: Problem Set 8"
#author: "Paul Schrimpf"
date: 2024-12-04
bibliography: ../../626.bib
---

$$
\def\Er{{\mathrm{E}}}
\def\En{{\mathbb{En}}}
\def\cov{{\mathrm{Cov}}}
\def\var{{\mathrm{Var}}}
\def\R{{\mathbb{R}}}
\newcommand\norm[1]{\left\lVert#1\right\rVert}
\def\rank{{\mathrm{rank}}}
\newcommand{\inpr}{ \overset{p^*_{\scriptscriptstyle n}}{\longrightarrow}}
\def\inprob{{\,{\buildrel p \over \rightarrow}\,}}
\def\indist{\,{\buildrel d \over \rightarrow}\,}
\DeclareMathOperator*{\plim}{plim}
$$

# Problem 1

Consider the linear model
$$
Y_i = \beta X_i^* + \epsilon_i
$$
with $\var(X_i^*)>0$, $\Er[\epsilon_i X_i^*] = 0$, and $\Er[\epsilon_i]=0$. Furthermore
suppose $X_i^* \in \{0,1\}$, but $X_i^*$ is unobserved. Instead, you
observe $X_i \in \{0,1\}$ and know that
$$
P(X_i = 1 | X_i^* = 1) = P(X_i=0 | X_i^*=0) = p
$$
where $p > 1/2$ is unknown.


## OLS is Inconsistent

Let $\hat{\beta}^{OLS} = \frac{\sum X_i Y_i}{\sum X_i^2}$ be the least
squares estimator. Let $\pi = P(X_i^*=1)$. Compute $\plim \hat{\beta}^{OLS}$ in terms of $p$, $\pi$, and $\beta$.

## Instrument?

Suppose you also observe $Z_i \in \{0,1\}$ with
$$
P(Z_i = 1 | X_i^* = 1) = P(Z_i=0 | X_i^*=0) = q
$$
where $q>1/2$, and $Z_i$ and $X_i$ are independent conditional on $X_i^*$.
Let $\hat{\beta}^{IV} = \frac{\sum Z_i Y_i}{\sum Z_i X_i}$
be the instrumental variable estimator. Compute $\plim \hat{\beta}^{IV}$

## Or Something Else?

Describe how $X$, $Y$, and $Z$ could be used to estimate $\beta$.

*Hint: think of $\beta$, $p$, $q$, and $\pi = P(X^*_i = 1)$ as four parameters to estimate, and come up with four moment conditions that involve these parameters.*

# Problem 2

Consider the model:
$$
y_{it} = \rho y_{it-1} + x_{it}'\beta + \alpha_i + u_{it}
$$
for $i=1,.., N$ and $t=1,...,T$. Assume observations are independent accross $i$, $x$ is strictly
exogenous, $\Er[x_{it} u_{is}] = 0 \forall s,t$, and $y_{it-1}$ is
weakly exogenous, $\Er[y_{it-1} u_{it+s}] = 0$ for $s \geq 0$.

## First Differences

Let $\Delta y_{it} = y_{it} - y_{it-1}$. Take differences of the model to eliminate $\alpha_i$, leaving
$$
\Delta y_{it} = \rho \Delta y_{it-1} + \Delta x_{it}'\beta + \Delta u_{it}.
$$
Will OLS on this equation be consistent?


## Fixed Effects Inconsistent

Show that for $T$ fixed and $N \to \infty$, the fixed effects
estimator, i.e. regressing $y_{it}$ on $y_{it-1} - \bar{y}_i$ and
$x_{it} - \bar{x}_i$, is not consistent. *Hint: what is $\Er[\bar{y}_i u_{it}]$?*

## GMM

Assume $T \geq 3$. Argue that $\Er[\Delta u_{it} y_{it-\ell}]=0$ for
$\ell \geq 2$, and that $\Er[\Delta y_{it-1} y_{it-\ell}] \neq 0$. Use this fact, along
with the assumptions above to derive a GMM estimator for $\rho$ and $\beta$.
