project:
  type: website
  render:
    - "*.qmd"
    - "!problemsets/*/sol*qmd"

website:
  title: "ECON 626"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus626.qmd
        text: Syllabus
      - about.qmd
      - slides.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
