---
title: "ECON 626: Econometric Theory I"
author: "Paul Schrimpf"
bibliography: 626.bib
---

# Part I: Basics

- [Measure slides](measure/measure.qmd)

   - Required reading: @song2021  Chapter 1
   - Supplementary reading: @pollard2002, @tao2011


-  [Probability slides](probability/probability.qmd)

   - Required reading: @song2021  Chapter 2
   - Supplementary reading: @pollard2002, @cinlar2011
   - Random Variables, and Distributions
   - Conditional Expectations and Conditional Distributions

- Family of Distributions : we will not cover in class, read and refer to @song2021 Chapter 3 as needed

- Basics of Inference

   - Required reading: @song2021 Chapter 4
   - [Identification](identification/identification.qmd)
   - [Estimation](estimation/estimation.qmd)
   - Hypothesis Testing

# Part II: Generalized Linear Model

- [Preliminaries of Projection Geometry](projection/projection.qmd)
- [Generalized Linear Models and Gauss-Markov Theorem](projection/projection.qmd)
- Tests of Linear Hypothesis

[Midterm Review](problemsets/midterm_review/midterm_review.qmd)

# Part III: Tools of Asymptotic Theory

- [Convergence in probability](asymptotics/inprobability.qmd)
- [Convergence in distribution](asymptotics/indistribution.qmd)
- [Delta Methods](asymptotics/indistribution.qmd)
- [Asymptotics of Least Squares](asymptotics/ols.qmd)

# Part IV

- [Difference in differences](did/did.qmd)

# Part V: Linear Models with Endogeneity

- [Endogeneity](iv/endogeneity.qmd)
- [Identification through IV and Inference](iv/iv.qmd)
- [Preview of GMM](gmm/gmm.qmd)
