---
title: "Syllabus for ECON 626: Econometric Theory I"
author: "Paul Schrimpf"
date: last-modified
---

## Basic Information

### Instructor

Paul Schrimpf

112 Iona

paul.schrimpf@ubc.ca

Office Hours: Wednesday 12:30pm-1:30pm

### TA

Yige Duan

yige.duan@gmail.com

Office Hours: Monxday 2-3pm


### Time and Place

Lecture: Mondays and Wednesdays 11:00am - 12:20pm, Iona 633

Discussion: Friday 1:30pm  - 2:50pm, Buchanan D209


### Textbooks

Our primary textbook will be notes written by Kyunchul Song. You can find them on Canvas. Other recommended (but not required) textbooks include:

- Bruce Hansen (2022) *Probability and Statistics for Economists* and *Econometrics*
- Fumio Hayashi (2000) *Econometrics*
- George Casella and Roger L. Berger (2002) *Statistical Inference*
- Takeshi Amemiya (1985) *Advanced Econometrics*


## Grading

### Problem Sets (30%)

There will be 6-9 problem sets. A problem set with the lowest grade
will be dropped from final grading.

### Midterm Exam (30%)

Given in class on Wednesday, October 26. Closed books and notes.
There will be no make-up exam for midterm. When a student is excused
from midterm exam, his or her grade will be based on reweighting of
the problem sets (40%) and the final exam (60%).

### Final Exam (40%)

Closed books and notes.


# Course Description

The course aims to equip students with introductory knowledge in
probability, statistics, and econometrics so that students become
familiar with basic concepts underlying empirical and methodological
research in economics.

# Outline

## Part I: Basics

  -  Probability
        - Random Variables, and Distributions
        - Conditional Expectations and Conditional Distributions
        - Family of Distributions
  - Basics of Inference
        - Estimation
        - Hypothesis Testing

## Part II: Generalized Linear Model

   - Preliminaries of Projection Geometry
   - Generalized Linear Models and Gauss-Markov Theorem
   - Tests of Linear Hypothesis

## Part III: Tools of Asymptotic Theory

   - Modes of Convergence
   - Slutsky’s Lemma/Continuous Mapping Theorem
   - Delta Methods

## Part V: Linear Models with Endogeneity

   - Identification and Endogeneity
   - Identification through IV and Inference



::: {.callout-note icon=false collapse="true"}
## Student Success

UBC provides resources to support student learning and to maintain healthy lifestyles but recognizes that sometimes crises arise and so there are additional resources to access including those for survivors of sexual violence. UBC values respect for the person and ideas of all members of the academic community. Harassment and discrimination are not tolerated nor is suppression of academic freedom. UBC provides appropriate accommodation for students with disabilities and for religious, spiritual and cultural observances. UBC values academic honesty and students are expected to acknowledge the ideas generated by others and to uphold the highest academic standards in all of their actions. Details of the policies and how to access support are available here: https://senate.ubc.ca/policies-resources-support-student-success/.

:::


::: {.callout-note icon=false collapse="true"}
## Policy on Academic Honesty

It is the policy of the Vancouver School of Economics to report all violations of UBC’s standards for academic integrity to the office of the Dean of Arts. All violations of academic integrity standards will result in a grade of zero on the relevant assessment (exam, paper, assignment etc.).  Students who do not have a previous offence may have the option to enter into a diversionary process with the Dean of Arts to resolve their misconduct (https://academicintegrity.ubc.ca/diversionary-process/). Any student who has a previous academic offence will be referred to the President’s Advisory Committee on Student Discipline (PACSD) (https://universitycounsel.ubc.ca/homepage/guides-and-resources/discipline/). PACSD may impose additional penalties including: a transcript notation indicating that the student has committed an academic offence, zero in the course, and/or suspension or expulsion from the University. You are personally responsible for understanding and following the UBC’s policies for academic integrity: https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/academic-honesty-and-standards.

:::


::: {.callout-note icon=false collapse="true"}
## Policy on Academic Concessions

There are only three acceptable grounds for academic concessions at UBC: unexpected changes in personal responsibilities that create a schedule conflict; medical circumstances; and compassionate grounds when the student experiences a traumatic event, sexual assault, or death in the family or of a close friend. Academic concessions for graded work and exams are granted for work that will be missed due to unexpected situations or circumstances. Situations that are expected (such as time constraints due to workload in other courses) or are predictable (such as being scheduled for paid work) are not grounds for academic concession.

Requests for academic concessions should be made before the due date for that graded work and/or the writing of the exam. UBC policy does not allow for concessions to students who have missed work because they have registered for a course after the due date for that work. You can read more about the rules for academic concessions here: https://students.ubc.ca/enrolment/academic-learning-resources/academic-concessions. Students in the Faculty of Arts who require a concession can apply for concessions using this form here: https://students.air.arts.ubc.ca/academic-concession-form/. Students in other Faculties should consult their faculty website on academic concessions. Please note that the role of the faculty advising office is to review the evidence and to either support or not support concession requests. The final decision to grant the request always rests with your instructor.
:::

::: {.callout-note icon=false collapse="true"}
## Policy on the Use of AI Learning Tools

The use of AI tools is permitted except where explicitly forbidden. However, that usage must be documented and attributed within your assessment(s). Students are responsible for all factual inaccuracies that are created by the use of AI tools.
:::
