---
title: "Measure"
author: "Paul Schrimpf"
date: last-modified
format:
  revealjs:
    theme: moon
    width: 1820
    height: 1000
    min-scale: 0.1
bibliography: ../626.bib

jupyter: julia-1.8
execute:
  cache: false
---

## References

- **@song2021 chapter 1** (which is the basis for these slides)
- @pollard2002
- @tao2011

# Measures

## Why Measure Theory?

::: {.incremental}
1. Simplifies some arguments
    - Example from @pollard2002, define independence as factorization of distribution functions
    $$ P(X \leq x \cap Y \leq y) = P(X \leq x) P(Y \leq y) $$
    - If $X_1,X_2,X_3, X_4$ are independent, show that
    $$ Y = X_1 X_2 \log\left(\frac{X_1^2 + X_2^3}{|X_1| + |X_2|}\right) $$
    is independent of
    $$ Z =  sin\left(X_3 + X_3^2 + X_3X_4 + X_4^2 \right) $$
::::

## Why Measure Theory?


1. Simplifies some arguments

::: {.incremental}

2. Unifies treatment
   - discrete vs continuous
   - uni- vs multi-variate
3. Resolves some difficulties with infinity

:::

## Measure Space

::: {.incremental}
1. A set $\Omega$
2. A collection of subsets, $\mathscr{F}$, of $\Omega$ that is a $\sigma$*-field* (aka $\sigma$*-algebra*) , that is
    1. $\Omega \in \mathscr{F}$
    2. If $A \in \mathscr{F}$, then $A^c \in \mathscr{F}$
    3. If $A_1, A_2, ... \in \mathscr{F}$, then
    $\cup_{j=1}^\infty A_j \in \mathscr{F}$
3. A measure, $\mu: \mathcal{F} \to [0, \infty]$ s.t.
    1. $\mu(\emptyset) = 0$
    2. If $A_1, A_2, ... \in \mathscr{F}$ are pairwise disjoint, then
    $\mu\left(\cup_{j=1}^\infty A_j \right) = \sum_{j=1}^\infty \mu(A_j)$
:::

::: {.notes}

Example of sigma fields

:::

## Measurable Function

- Given a topology on $\Omega$, the **Borel** $\sigma$-**field**, $\mathscr{B}(\Omega)$, is the smallest $\sigma$-field containing all open subsets of $\Omega$

::: {.notes}

When working with $R^d$, we will generally use $\mathscr{B}(\mathbf{R}^d)$ as our $\sigma$-field.

:::

- $f: \Omega \to \mathbf{R}$ is ($\mathscr{F}$-)**measurable** if $\forall$
$B \in \mathscr{B}(\mathbf{R})$, $f^{-1}(B) \in \mathscr{F}$

- a statement holds *almost everywhere* (a.e.) if the measure of the set where the statement is false is 0

<!-- ::: {.callout-note icon=false} -->

<!-- ### Exercise -->

<!-- Show that if $f_1, f_2, f_3, ...$ are measurable, then -->
<!-- $\sum_{j=1}^\infty f_j$ is measurable -->

<!-- ::: -->

# Integration

## Simple Functions

- Assume $\mu(\Omega) < \infty$
- $f$ is a **simple function** if
$f = \sum_{j=1}^n a_j 1\{\omega \in E_j \}$ for $a_j \in \mathbf{R}$ and
$E_j \in \mathscr{F}$
- Integral of simple functions:
$$ \int f d \mu = \sum_{j=1}^n a_j \mu(E_j) $$

---

::: {.callout-note icon=false}

### Exercise

Show that if $f$ is simple, then $f$ is measurable.

:::


::: {.callout-note icon=false}

### Exercise

Show that if $f$ and $g$ are simple, then

1. If $f \geq 0$ a.e., then $\int f d\mu \geq 0$

2. $\forall a \in \mathbf{R}$ , $\int a f d\mu = a \int f d\mu$

3. $\int (f + g) d\mu = \int f d\mu + \int g d \mu$

:::

## Bounded Functions

- Let $E$ be such that $\mu(E)<\infty$
- Let $f$ be bounded function and $f(x) = 0 \forall x \in E^c$
- Define:
$$
 \int f d\mu \equiv \sup_{\varphi \leq f: \varphi \text{ simple}} \int \varphi d\mu =\inf_{\varphi \geq f: \varphi \text{ simple}} \int \varphi d\mu
$$

----

::: {.callout-note icon=false}

### Exercise

Show the second equality above.

:::

```{julia}
using Pkg
Pkg.activate(".")
using Plots
Ω = range(1., 6., 500)
f(ω) = max( -(3 - ω)^2 + ω + sin(3*ω), 0.0)
p = plot(Ω, f.(Ω), label="f(ω)")
M = maximum(abs.(f.(Ω)))*1.05
n = 10
k(ω) = minimum(j for j ∈ 0:n if M/n*j > f(ω))
ψ(ω) = M/n*k(ω)*(f(ω) > 0.0)
ϕ(ω)  = M/n*(k(ω)-1)*(f(ω) > 0.0)
plot!(Ω,ψ, label="ψₙ(ω)")
plot!(Ω, ϕ,label="ϕₙ(ω)")
```
<!-- graph showing f, \psi_n, \varphi_n -->
----

::: {.callout-note icon=false}

### Exercise

Show that for all bounded $f$ and $g$ that vanish outside a finite measure set,

1. If $f \geq 0$ a.e., then $\int f d\mu \geq 0$

2. $\forall a \in \mathbf{R}$ , $\int a f d\mu = a \int f d\mu$

3. $\int (f + g) d\mu = \int f d\mu + \int g d \mu$

:::

## Nonnegative Functions

- If $f \geq 0$, define
$$
\int fd\mu =\sup_{f_n \leq f \text{ simple, bounded+}} \int f_{n}d\mu
$$

---

::: {.callout-note icon=false}

### Exercise

Show that for all $f \geq 0$,

1. If $f \geq 0$ a.e., then $\int f d\mu \geq 0$

2. $\forall a \in \mathbf{R}$ , $\int a f d\mu = a \int f d\mu$

3. $\int (f + g) d\mu = \int f d\mu + \int g d \mu$

:::

## Measurable Functions

- If $f$ is measurable, let $f^{+} = \max\{f, 0\}$ and
$f^{-} = \max\{-f, 0\}$ and define the *Lesbegue integral*

$$ \int f d\mu = \int f^{+} d\mu - \int f^{-} d\mu $$

---

::: {.callout-note icon=false}

### Exercise

Show that for all measurable $f$

1. If $f \geq 0$ a.e., then $\int f d\mu \geq 0$

2. $\forall a \in \mathbf{R}$ , $\int a f d\mu = a \int f d\mu$

3. $\int (f + g) d\mu = \int f d\mu + \int g d \mu$

:::


# Radon-Nikodym Derivatives

## Finite Measure

- Measure $\mu$ is *finite* if $\mu(\Omega)$ is finite
- $\mu$ is $\sigma$-*finite* if $\exists$ $\{A_n\}_{n=1}^\infty \in
\mathscr{F}$ s.t. $\mu(A_n)$ is finite $\forall n$ and
$\cup_{n=1}^\infty A_n = \Omega$

::: {.callout-note icon=false}

### Exercise

Let $\Omega$ be countable with any $\mathscr{F}$, define $\mu(A)$ as the number of elements of $A$. Show $\mu$ is $\sigma$ finite.


:::


## Lebesgue Measure

::: {.callout-warning icon=false}

### Theorem

There exists a unique $\sigma$-finite measure $\mu$ on $(\mathbf{R},\mathscr{B}(\mathbf{R}))$  such that for any $a\leq b$ with $a,b\in \mathbf{R}$,
$$
\mu ((a,b])=b-a
$$

:::

## Absolute Continuity

- Measure $\nu$ is **absolutely continuous** with respect to $\mu$ if
for $A \in \mathscr{F}$, $\mu(A) = 0$ implies $\nu(A) = 0$
    - denotate as $\nu \ll \mu$
    - $\mu$ is called a **dominating measure**

::: {.notes}

Relation with continuity?

:::

## Radon-Nikodym Derivative

::: {.callout-warning icon=false}

### Theorem

Let $(\Omega,\mathscr{F},\mu)$ be a measure space, and let $\nu$
and $\mu$ be $\sigma$-finite measures defined on $\mathscr{F}$ and $\nu \ll \mu$. Then there is
a nonnegative measurable function $f$ such that for each set $A\in \mathscr{F}$,
$$
\nu (A)=\int_{A}fd\mu
$$
For any such $f$ and $g$, $\mu (\{\omega \in \Omega:f(\omega )\neq g(\omega )\})=0$

:::

::: {.notes}

Denote $f = \frac{d\nu}{d\mu}

Exercise: show coincides with usual derivative?

:::

# Convergence Theorems

## Sequences of Sets

- $\{E_n\}_{n \geq 1} \in \mathscr{F}$
    - *increasing* if $E_1 \subset E_2 \subset ...$
    - *decreasing* if $E_1 \supset E_2 \supset ...$
    - *monotone* if either increasing or decreasing
- For increasing $E_n$, define
$\lim_{n \to \infty} E_n =\cup_{n=1}^\infty E_n$
- For decreasing $E_n$, define
$\lim_{n \to \infty} E_n =\cap_{n=1}^\infty E_n$

## Continuity of Measure

::: {.callout-warning icon=false}

### Lemma

Suppose that $\{E_{n}\}$ is a monotone sequence of events. Then
$$
\mu \left( \lim_{n\rightarrow \infty}E_{n}\right) =\lim_{n\rightarrow \infty }\mu (E_{n}).
$$

:::

## Monotone Convergence Theorem

::: {.callout-warning icon=false}

### Lemma


If $f_n:\Omega \to \mathbf{R}$ are measurable, $f_{n}\geq 0$, and for each $\omega \in \Omega$,
$f_{n}(\omega )\uparrow f(\omega )$, then $\int f_{n}d\mu \uparrow \int fd\mu$ as $n\rightarrow \infty$

:::

## Fatou's Lemma

::: {.callout-warning icon=false}

### Lemma

If $f_n:\Omega \to \mathbf{R}$ are measurable, $f_{n}\geq 0$, then
$$
\int \left( \text{liminf}_{n\rightarrow \infty }f_{n}d\mu \right) \leq \text{liminf}_{n\rightarrow \infty }\int f_{n}d\mu
$$

:::


## Dominated Convergence Theorem

::: {.callout-warning icon=false}

### Lemma

If $f_n:\Omega \to \mathbf{R}$ are measurable, and for each $\omega \in \Omega$, $f_{n}(\omega )\rightarrow f(\omega ).$ Furthermore, for some $g\geq 0$ such that $\int gd\mu <\infty$, $|f_{n}|\leq g$ for each $n\geq 1$. Then, $\int f_{n}d\mu \rightarrow \int fd\mu$

:::

::: {.notes}

The measurable condition here can be dropped and outermeasure used
instead. This simplifies some proofs in asymptotic theory.

:::


# References
